bien/config/routes.rb
Rails.application.routes.draw do

resources :reviews

root "reviews#index"

end

bien/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bien/app/models/review.rb
class Review < ApplicationRecord

  geocoded_by :address
  after_validation :geocode


 validates :title, presence: true
 validates :body, length: {minimum: 10}
 validates :score, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
 validates :restaurant, presence: true
 validates :address, presence: true

def to_param
  id.to_s + "-" + title.parameterize 
end

end

bien/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bien/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def index 
   # this is our list page for our reviews
   @price = params[:price]
   @cuisine = params[:cuisine]
   @location = params[:location]

   # start with all the reviews
   @reviews = Review.all

   # filtering by price
   if @price.present?    
     @reviews = @reviews.where(price: @price)
   end

   # filter by cuisine
   if @cuisine.present?
    @reviews = @reviews.where(cuisine: @cuisine)
   end

   # search near the location
   if @location.present?
     @reviews = @reviews.near(@location)
   end

end 

def new
  # the form for adding a new review
 @review = Review.new

end


def create 
  # take info from the form and add it to the database
  @review = Review.new(form_params)

  # save this to the database
  if @review.save
     redirect_to root_path 

  else 

    # show the view for new.html.erb
    render "new"
  end

end

def show 
   #individual review page 
   @review = Review.find(params[:id])

end 

def destroy 
 # find the individual review
 @review = Review.find(params[:id])

 
# destroy 

@review.destroy

 # redirect to the home page 
redirect_to root_path

end

def edit

   # find the individual review (to edit)
   @review = Review.find(params[:id])

end

def update 
    # find the individual review
    @review = Review.find(params[:id])

    # update with the new info from the form
    if @review.update(form_params)
    
        # redirect somewhere new 
        redirect_to review_path(@review)
    else 
      render "edit"
    end
end 

def form_params 

    params.require(:review).permit(:title, :restaurant, :ambiance, :body, 
      :address,:price, :score)   

end



end

bien/app/helpers/application_helper.rb
module ApplicationHelper
end

bien/app/helpers/reviews_helper.rb
module ReviewsHelper
end

bien/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%=content_for :page_title %> - Bien Reviews - the best restaurant in the world  </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <header>
     <nav>
       <h1> 
     
     <%= link_to root_path do %>
        <%= image_tag "bien-logo.svg" %>
      <% end %>
      </h1>
    </nav>

     <h2> The best restaurants in the world </h2>
     
     <nav>
      <%= link_to "Add a review", new_review_path %>
     </nav>
  </header>

  <main>
    <%= yield %>
  </main>

    <footer>
     Copyright 2017 Bien Reviews
    </footer>


  </body>
</html>

bien/app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>

    <% if @review.errors.any? %> 

       <div class="errors">

       <% @review.errors.full_messages.each do |message| %> 

         <p> <%= message %> </p>

        <% end %>

       </div>

    <% end %> 


    <p>
      <%= f.label :title %> 
      <%= f.text_field :title %> 
    </p>

    <p>
      <%= f.label :restaurant %> 
      <%= f.text_field :restaurant %> 
    </p>

    <p>
      <%= f.label :address %> 
      <%= f.text_field :address %> 
    </p>

    <p>
      <%= f.label :cuisine %> 
      <%= f.text_field :cuisine %> 
    </p>

    <p>
      <%= f.label :price %> 
      <%= f.text_field :price %> 
    </p>
  
    <p>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </p>
    
    <p>
      <%= f.label :score %>
      <%= f.number_field :score %>
    </p>

    <p>
    <%= f.label :ambiance %>
    <%= f.text_field :score %>
    </p>

  
    <%= f.submit "Save review" %>
  
  
  
  <% end %>

bien/app/views/reviews/edit.html.erb
<h3> Edit your restaurant review! </h3>

<%= render "form" %>

bien/app/views/reviews/index.html.erb
<% content_for :page_title, "Homepage" %>

<nav class="filters">
   <%= link_to "All restaurants", root_path %>

   <div>
   <%= link_to "$", root_path(price: 1, cuisine: @cuisine, location: @location)%>
   <%= link_to "$$", root_path(price: 2, cuisine: @cuisine, location: @location)%>
   <%= link_to "$$$", root_path(price: 3, cuisine: @cuisine, location: @location)%>
  </div>

  <div>
   <%= link_to "Indian", root_path(cuisine: "Indian", price: @price, @location) %>
   <%= link_to "Mexican", root_path(cuisine: "Mexican", price: @price, @location) %>
   <%= link_to "American", root_path(cuisine: "American", price: @price, @location) %>
  </div>

  <form action="/">
    <input type="text" name="location" 
      placeholder="search location..." value="<%= @location %>">
  
       <input type="hidden" name="price" value="<%= @price %>">5.
       <input type="hidden" name="cuisine" value="<%= @cuisine %>">
      </form>

</nav>


<% @reviews.each do |review| %>

  <div class="review"> 
  
   <%= link_to review.title, review_path(review) %> 
  
  </div>


<% end %>

bien/app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3> Add your new restaurant review! </h3>

<%= render "form" %>

bien/app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %> 

<h1> <%= @review.title %> </h1>

<h2> <%= @review.restaurant %> </h2>

<div class="score">
   <%= @review.score %> / 10
</div>

<% if @review.ambiance.present? %>

<div class="ambiance">
   Ambiance <%= @review.ambiance %> / 10
</div>

<% end %>

<% if @review.price.present? %>

<div class="price">
   Price: <%= @review.price %> / 10
</div>

<% end %>

<% if @review.cuisine.present? %>

<div class="ambiance">
   Cuisine: <%= @review.cuisine %> / 10
</div>

<% end %>

<div class="body">

  <%= simple_format @review.body %>

</div>

<div class="actions">

  <%= link_to "Edit this review", edit_review_path(@review) %>
  <%= link_to "Delete this review", review_path(@review), method: :delete, data: {confirm: "Are you sure?"} %>

</div>